import path from 'node:path';
import type { FileInfo } from '../analyzers/base.js';
import type { ReactInfo } from '../analyzers/react.js';
import type { NestJSInfo } from '../analyzers/nestjs.js';
import type { DepGraph } from '../utils/dep-graph.js';

export interface ClaudeMdOptions {
  root: string;
  files: FileInfo[];
  graph: DepGraph;
  reactInfo?: ReactInfo;
  nestjsInfo?: NestJSInfo;
  frameworks: string[];
}

/**
 * Generate CLAUDE.md content for a repository.
 */
export function generateClaudeMd(opts: ClaudeMdOptions): string {
  const { root, files, graph, reactInfo, nestjsInfo, frameworks } = opts;
  const date = new Date().toISOString().split('T')[0];
  const lines: string[] = [];

  lines.push(`# Architecture Overview`);
  lines.push(`> Generated by [lumina](https://github.com/namcv/lumina) on ${date}`);
  lines.push(`> This file is auto-generated. Do not edit manually.`);
  lines.push(``);

  // Review workflow instructions for Claude
  lines.push(`## Code Review Instructions`);
  lines.push(`**When reviewing a merge request or pull request, follow this workflow:**`);
  lines.push(``);
  lines.push(`1. Run \`lumina review --base <base-branch>\` to get the focused review context`);
  lines.push(`2. Read the generated review context — it lists exactly which files changed and which are impacted`);
  lines.push(`3. **Only review files listed in that context** — do not scan the full source tree`);
  lines.push(`4. Use \`lumina context --file <path>\` to get deep context for any specific file`);
  lines.push(``);
  lines.push(`> This ensures reviews are focused on the actual blast radius of the change, not the entire codebase.`);
  lines.push(``);

  // Tech stack summary
  lines.push(`## Tech Stack`);
  lines.push(`- **Framework**: ${frameworks.length > 0 ? frameworks.join(', ') : 'Unknown'}`);
  lines.push(`- **Total source files**: ${files.length}`);
  lines.push(`- **Root**: \`${root}\``);
  lines.push(``);

  // High-impact files
  const highImpact = files
    .map((f) => ({ f, count: graph.getImportedBy(f.path).length }))
    .filter(({ count }) => count >= 3)
    .sort((a, b) => b.count - a.count)
    .slice(0, 10);

  if (highImpact.length > 0) {
    lines.push(`## High-Impact Files`);
    lines.push(`Files imported by many others — changes here have wide blast radius:`);
    lines.push(``);
    for (const { f, count } of highImpact) {
      const label = count >= 10 ? '🔴 critical' : count >= 5 ? '🟡 high' : '🟢 medium';
      lines.push(`- \`${f.relativePath}\` ← imported by **${count}** files (${label})`);
    }
    lines.push(``);
  }

  // NestJS section
  if (nestjsInfo && frameworks.includes('nestjs')) {
    lines.push(`## NestJS Architecture`);
    lines.push(``);

    if (nestjsInfo.modules.length > 0) {
      lines.push(`### Modules`);
      for (const mod of nestjsInfo.modules) {
        lines.push(`#### ${mod.name} (\`${mod.file}\`)`);
        if (mod.controllers.length > 0) {
          lines.push(`- **Controllers**: ${mod.controllers.join(', ')}`);
        }
        if (mod.providers.length > 0) {
          lines.push(`- **Providers**: ${mod.providers.join(', ')}`);
        }
      }
      lines.push(``);
    }

    if (nestjsInfo.controllers.length > 0) {
      lines.push(`### Controllers (${nestjsInfo.controllers.length})`);
      for (const f of nestjsInfo.controllers) lines.push(`- \`${f}\``);
      lines.push(``);
    }

    if (nestjsInfo.services.length > 0) {
      lines.push(`### Services / Providers (${nestjsInfo.services.length})`);
      for (const f of nestjsInfo.services) lines.push(`- \`${f}\``);
      lines.push(``);
    }

    if (nestjsInfo.guards.length > 0) {
      lines.push(`### Guards (${nestjsInfo.guards.length})`);
      for (const f of nestjsInfo.guards) lines.push(`- \`${f}\``);
      lines.push(``);
    }

    if (nestjsInfo.interceptors.length > 0) {
      lines.push(`### Interceptors (${nestjsInfo.interceptors.length})`);
      for (const f of nestjsInfo.interceptors) lines.push(`- \`${f}\``);
      lines.push(``);
    }
  }

  // React section
  if (reactInfo && frameworks.includes('react')) {
    lines.push(`## React Architecture`);
    lines.push(``);

    // Group components by directory
    const componentsByDir = groupByDir(reactInfo.components);
    lines.push(`### Components (${reactInfo.components.length} total)`);
    for (const [dir, comps] of componentsByDir) {
      lines.push(`- **${dir || '.'}** → ${comps.length} component${comps.length > 1 ? 's' : ''}`);
    }
    lines.push(``);

    if (reactInfo.hooks.length > 0) {
      lines.push(`### Custom Hooks (${reactInfo.hooks.length})`);
      for (const f of reactInfo.hooks) lines.push(`- \`${f}\``);
      lines.push(``);
    }

    if (reactInfo.contexts.length > 0) {
      lines.push(`### Contexts (${reactInfo.contexts.length})`);
      for (const f of reactInfo.contexts) lines.push(`- \`${f}\``);
      lines.push(``);
    }

    if (reactInfo.hasRouter) {
      lines.push(`> Router: React Router detected`);
      lines.push(``);
    }
  }

  // Source map reference
  lines.push(`## Lumina Commands`);
  lines.push(`Machine-readable dependency graph: \`.claude/source-map.json\``);
  lines.push(``);
  lines.push('```bash');
  lines.push(`# Get focused review scope for an MR`);
  lines.push(`lumina review --base main -o .claude/review-context.md`);
  lines.push(``);
  lines.push(`# Get deep context for a specific file`);
  lines.push(`lumina context --file <path-to-file>`);
  lines.push(``);
  lines.push(`# Show all files impacted by a change`);
  lines.push(`lumina impact --file <path-to-file>`);
  lines.push(``);
  lines.push(`# View interactive dependency graph`);
  lines.push(`lumina graph --open`);
  lines.push('```');

  return lines.join('\n');
}

function groupByDir(files: string[]): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const f of files) {
    const dir = path.dirname(f);
    if (!map.has(dir)) map.set(dir, []);
    map.get(dir)!.push(f);
  }
  return map;
}
