import type { SourceMapOutput } from './graph.js';

export interface ApiMatchSummary {
  matched: number;
  unmatchedFrontend: Array<{ method: string; url: string; file: string }>;
  unmatchedBackend: Array<{ method: string; url: string; file: string }>;
}

/**
 * Generate HEALTH.md content from a source map.
 */
export function generateHealthReport(sourceMap: SourceMapOutput, apiMatch?: ApiMatchSummary): string {
  const date = new Date().toISOString().split('T')[0];
  const entries = Object.entries(sourceMap.files);
  const lines: string[] = [];

  // ── Summary ────────────────────────────────────────────────────────────────
  const aloneFiles = entries.filter(([, f]) => f.importedByCount === 0 && !(f.imports.length === 0 && f.type === 'unknown'));
  const highRiskFiles = entries.filter(([, f]) => f.riskScore > 0).sort((a, b) => b[1].riskScore - a[1].riskScore);
  const filesWithUnused = entries.filter(([, f]) => f.unusedExports.length > 0);
  const complexityScores = entries.map(([, f]) => f.complexity);
  const avgComplexity = complexityScores.length
    ? Math.round((complexityScores.reduce((a, b) => a + b, 0) / complexityScores.length) * 10) / 10
    : 0;
  const highComplexity = entries.filter(([, f]) => f.complexity > 10);

  lines.push(`# Architecture Health Report`);
  lines.push(`> Generated by repo-context-mapper on ${date}`);
  lines.push(``);
  lines.push(`## Summary`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total files | ${sourceMap.totalFiles} |`);
  lines.push(`| Circular dependencies | ${sourceMap.cycles.length === 0 ? '✅ None' : `🔴 ${sourceMap.cycles.length}`} |`);
  lines.push(`| Unused components (alone) | ${aloneFiles.length === 0 ? '✅ None' : `⚠️ ${aloneFiles.length}`} |`);
  lines.push(`| Duplicate file names | ${sourceMap.duplicates.length === 0 ? '✅ None' : `🔁 ${sourceMap.duplicates.length} groups`} |`);
  lines.push(`| Files with unused exports | ${filesWithUnused.length} |`);
  lines.push(`| Avg complexity score | ${avgComplexity} |`);
  lines.push(`| High complexity files (>10) | ${highComplexity.length} |`);
  if (apiMatch) {
    lines.push(`| API matched routes | ✅ ${apiMatch.matched} |`);
    lines.push(`| Unmatched frontend calls | ${apiMatch.unmatchedFrontend.length === 0 ? '✅ 0' : `❌ ${apiMatch.unmatchedFrontend.length}`} |`);
    lines.push(`| Dead backend routes | ${apiMatch.unmatchedBackend.length === 0 ? '✅ 0' : `🔇 ${apiMatch.unmatchedBackend.length}`} |`);
  }
  lines.push(``);

  // ── Circular dependencies ──────────────────────────────────────────────────
  lines.push(`## 🔴 Circular Dependencies`);
  lines.push(``);
  if (sourceMap.cycles.length === 0) {
    lines.push(`No circular dependencies found. ✅`);
  } else {
    lines.push(`Found **${sourceMap.cycles.length}** circular import cycle(s):`);
    lines.push(``);
    sourceMap.cycles.slice(0, 20).forEach((cycle, i) => {
      lines.push(`**Cycle ${i + 1}:** ${cycle.map(f => `\`${f}\``).join(' → ')}`);
    });
    if (sourceMap.cycles.length > 20) lines.push(`_...and ${sourceMap.cycles.length - 20} more_`);
  }
  lines.push(``);

  // ── Unused components ──────────────────────────────────────────────────────
  lines.push(`## ⚠️ Unused Components (Alone)`);
  lines.push(``);
  if (aloneFiles.length === 0) {
    lines.push(`All components are used. ✅`);
  } else {
    lines.push(`${aloneFiles.length} file(s) are defined but never imported:`);
    lines.push(``);
    // Group by type
    const byType = new Map<string, string[]>();
    for (const [file, f] of aloneFiles) {
      const t = f.type;
      if (!byType.has(t)) byType.set(t, []);
      byType.get(t)!.push(file);
    }
    for (const [type, files] of byType) {
      lines.push(`**${type}** (${files.length})`);
      files.slice(0, 10).forEach(f => lines.push(`- \`${f}\``));
      if (files.length > 10) lines.push(`  _...and ${files.length - 10} more_`);
      lines.push(``);
    }
  }

  // ── Duplicates ─────────────────────────────────────────────────────────────
  lines.push(`## 🔁 Duplicate File Names`);
  lines.push(``);
  if (sourceMap.duplicates.length === 0) {
    lines.push(`No duplicate file names found. ✅`);
  } else {
    lines.push(`${sourceMap.duplicates.length} group(s) of files share the same name:`);
    lines.push(``);
    sourceMap.duplicates.slice(0, 20).forEach(({ name, files }) => {
      lines.push(`**\`${name}\`** — ${files.length} files`);
      files.forEach(f => lines.push(`- \`${f}\``));
      lines.push(``);
    });
  }

  // ── High-risk files ────────────────────────────────────────────────────────
  lines.push(`## 🔥 High-Risk Files (Git Churn × Fan-out)`);
  lines.push(``);
  if (highRiskFiles.length === 0) {
    lines.push(`No git data available (run inside a git repo).`);
  } else {
    lines.push(`Top 10 files most likely to cause regressions when changed:`);
    lines.push(``);
    lines.push(`| File | Risk Score | Churn | Imported By |`);
    lines.push(`|------|-----------|-------|-------------|`);
    highRiskFiles.slice(0, 10).forEach(([file, f]) => {
      lines.push(`| \`${file}\` | ${f.riskScore} | ${f.gitChurn} commits | ${f.importedByCount} files |`);
    });
  }
  lines.push(``);

  // ── Complexity ─────────────────────────────────────────────────────────────
  lines.push(`## 📊 Complexity Distribution`);
  lines.push(``);
  const low = entries.filter(([, f]) => f.complexity <= 3).length;
  const med = entries.filter(([, f]) => f.complexity > 3 && f.complexity <= 10).length;
  const high = entries.filter(([, f]) => f.complexity > 10).length;
  lines.push(`| Level | Range | Count |`);
  lines.push(`|-------|-------|-------|`);
  lines.push(`| Low | ≤ 3 | ${low} files |`);
  lines.push(`| Medium | 3–10 | ${med} files |`);
  lines.push(`| High | > 10 | ${high} files |`);
  lines.push(``);
  if (highComplexity.length > 0) {
    lines.push(`Top complex files:`);
    highComplexity
      .sort((a, b) => b[1].complexity - a[1].complexity)
      .slice(0, 10)
      .forEach(([file, f]) => lines.push(`- \`${file}\` — score: ${f.complexity} (${f.linesOfCode} loc, ${f.importedByCount} importers)`));
    lines.push(``);
  }

  // ── Unused exports ─────────────────────────────────────────────────────────
  if (filesWithUnused.length > 0) {
    lines.push(`## 🗑️ Unused Exports`);
    lines.push(``);
    lines.push(`${filesWithUnused.length} file(s) have exports that appear unused:`);
    lines.push(``);
    filesWithUnused.slice(0, 15).forEach(([file, f]) => {
      lines.push(`- \`${file}\`: ${f.unusedExports.map(e => `\`${e}\``).join(', ')}`);
    });
    if (filesWithUnused.length > 15) lines.push(`_...and ${filesWithUnused.length - 15} more_`);
    lines.push(``);
  }

  // ── API match ──────────────────────────────────────────────────────────────
  if (apiMatch) {
    lines.push(`## 🔗 API Contract`);
    lines.push(``);
    lines.push(`- ✅ Matched routes: **${apiMatch.matched}**`);
    lines.push(``);
    if (apiMatch.unmatchedFrontend.length > 0) {
      lines.push(`### ❌ Frontend calls with no backend route (potential 404)`);
      apiMatch.unmatchedFrontend.forEach(c => lines.push(`- \`${c.method} ${c.url}\` — \`${c.file}\``));
      lines.push(``);
    }
    if (apiMatch.unmatchedBackend.length > 0) {
      lines.push(`### 🔇 Backend routes with no frontend caller (dead endpoints)`);
      apiMatch.unmatchedBackend.forEach(r => lines.push(`- \`${r.method} ${r.url}\` — \`${r.file}\``));
      lines.push(``);
    }
  }

  return lines.join('\n');
}
