import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import pc from 'picocolors';
import { DepGraph } from '../../utils/dep-graph.js';
import { calculateImpact, renderImpactMarkdown } from '../../generators/impact-report.js';
import type { SourceMapOutput } from '../../generators/graph.js';

export async function prCommentCommand(opts: {
  root?: string;
  base?: string;
  output?: string;
}): Promise<void> {
  const root = path.resolve(opts.root ?? process.cwd());
  const base = opts.base ?? 'main';
  const sourceMapPath = path.join(root, '.claude', 'source-map.json');

  if (!fs.existsSync(sourceMapPath)) {
    console.error(pc.red('✗') + ' source-map.json not found. Run `repo-mapper analyze` first.');
    process.exit(1);
  }

  // Get changed files from git
  let changedFiles: string[] = [];
  try {
    const out = execSync(`git -C "${root}" diff --name-only ${base}...HEAD`, {
      encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 10000,
    });
    changedFiles = out.trim().split('\n').filter(Boolean);
  } catch {
    console.error(pc.red('✗') + ` Could not run git diff against base: ${base}`);
    process.exit(1);
  }

  if (changedFiles.length === 0) {
    console.log(pc.yellow('No changed files detected.'));
    return;
  }

  // Reconstruct graph from source-map.json
  const saved: SourceMapOutput = JSON.parse(fs.readFileSync(sourceMapPath, 'utf-8'));
  const graph = new DepGraph();
  const savedRoot = saved.root;

  for (const [rel, data] of Object.entries(saved.files)) {
    const abs = path.join(savedRoot, rel);
    graph.addFile(abs);
    for (const imp of data.imports) graph.addEdge(abs, path.join(savedRoot, imp));
  }

  // Build impact for each changed file
  const impacts: Array<{ file: string; total: number; critical: string[]; riskScore: number }> = [];
  let totalImpacted = new Set<string>();

  for (const rel of changedFiles) {
    const abs = path.join(root, rel);
    const result = calculateImpact(abs, root, graph);
    result.impacted.forEach(i => totalImpacted.add(i.file));
    const fileData = saved.files[rel];
    impacts.push({
      file: rel,
      total: result.totalImpacted,
      critical: result.criticalFiles,
      riskScore: fileData?.riskScore ?? 0,
    });
  }

  // Sort: highest impact first
  impacts.sort((a, b) => b.total - a.total || b.riskScore - a.riskScore);

  // Generate markdown comment
  const date = new Date().toISOString().split('T')[0];
  const md: string[] = [];
  md.push(`## 🔍 Impact Analysis — repo-context-mapper`);
  md.push(`> Generated on ${date} | Base: \`${base}\``);
  md.push(``);
  md.push(`### Changed Files (${changedFiles.length})`);
  md.push(``);

  for (const impact of impacts) {
    const fileData = saved.files[impact.file];
    const risk = impact.riskScore > 20 ? ' 🔥' : impact.riskScore > 5 ? ' ⚠️' : '';
    md.push(`#### \`${impact.file}\`${risk}`);
    if (fileData) {
      md.push(`- **Type**: ${fileData.type} | **Complexity**: ${fileData.complexity} | **Risk score**: ${fileData.riskScore}`);
    }
    md.push(`- **Impacted files**: ${impact.total}`);
    if (impact.critical.length > 0) {
      md.push(`- **Critical (high fan-out affected)**:`);
      impact.critical.slice(0, 5).forEach(f => md.push(`  - \`${f}\``));
    }
    md.push(``);
  }

  md.push(`### Total Unique Files Impacted: **${totalImpacted.size}**`);
  md.push(``);

  // Cycles warning
  if (saved.cycles.length > 0) {
    md.push(`> ⚠️ **Warning**: This repo has ${saved.cycles.length} circular dependency cycle(s). Changes may have unexpected transitive effects.`);
    md.push(``);
  }

  md.push(`<details><summary>About this report</summary>`);
  md.push(`Generated by <a href="https://www.npmjs.com/package/repo-context-mapper">repo-context-mapper</a>. Run <code>npx repo-mapper analyze</code> to update.</details>`);

  const comment = md.join('\n');
  console.log(comment);

  if (opts.output) {
    const outPath = path.resolve(opts.output);
    fs.writeFileSync(outPath, comment, 'utf-8');
    console.error(pc.dim(`\nSaved to: ${outPath}`));
  }
}
