import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import pc from 'picocolors';
import { DepGraph } from '../../utils/dep-graph.js';
import type { SourceMapOutput } from '../../generators/graph.js';

interface ReviewFile {
  path: string;       // relative path
  reason: 'changed' | 'impacted';
  type: string;
  complexity: number;
  riskScore: number;
  importedByCount: number;
}

export async function reviewCommand(opts: {
  root?: string;
  base?: string;
  output?: string;
  json?: boolean;
}): Promise<void> {
  const root = path.resolve(opts.root ?? process.cwd());
  const base = opts.base ?? 'main';
  const sourceMapPath = path.join(root, '.claude', 'source-map.json');

  if (!fs.existsSync(sourceMapPath)) {
    console.error(pc.red('✗') + ' source-map.json not found. Run `lumina analyze` first.');
    process.exit(1);
  }

  // Get changed files from git diff
  let changedFiles: string[] = [];
  try {
    const out = execSync(`git -C "${root}" diff --name-only ${base}...HEAD`, {
      encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'], timeout: 10000,
    });
    changedFiles = out.trim().split('\n').filter(Boolean);
  } catch {
    console.error(pc.red('✗') + ` Could not run git diff against base: ${base}`);
    process.exit(1);
  }

  if (changedFiles.length === 0) {
    console.log(pc.yellow('⚠ No changed files detected.'));
    return;
  }

  // Load source map
  const saved: SourceMapOutput = JSON.parse(fs.readFileSync(sourceMapPath, 'utf-8'));
  const savedRoot = saved.root;

  // Reconstruct graph
  const graph = new DepGraph();
  for (const [rel, data] of Object.entries(saved.files)) {
    const abs = path.join(savedRoot, rel);
    graph.addFile(abs);
    for (const imp of data.imports) graph.addEdge(abs, path.join(savedRoot, imp));
  }

  // BFS: find all impacted files from changed files
  const changedSet = new Set(changedFiles);
  const impactedSet = new Set<string>();

  for (const rel of changedFiles) {
    const abs = path.join(root, rel);
    const impacted = graph.getImpacted(abs);
    for (const imp of impacted) {
      const impRel = path.relative(root, imp.file);
      if (!changedSet.has(impRel)) {
        impactedSet.add(impRel);
      }
    }
  }

  // Build review file list
  const reviewFiles: ReviewFile[] = [];

  for (const rel of changedFiles) {
    const data = saved.files[rel];
    if (!data) continue;
    reviewFiles.push({
      path: rel,
      reason: 'changed',
      type: data.type,
      complexity: data.complexity,
      riskScore: data.riskScore,
      importedByCount: data.importedByCount,
    });
  }

  for (const rel of [...impactedSet].sort()) {
    const data = saved.files[rel];
    if (!data) continue;
    reviewFiles.push({
      path: rel,
      reason: 'impacted',
      type: data.type,
      complexity: data.complexity,
      riskScore: data.riskScore,
      importedByCount: data.importedByCount,
    });
  }

  // Sort impacted files by risk score descending
  const changed = reviewFiles.filter(f => f.reason === 'changed');
  const impacted = reviewFiles
    .filter(f => f.reason === 'impacted')
    .sort((a, b) => b.riskScore - a.riskScore || b.importedByCount - a.importedByCount);

  const allFiles = [...changed, ...impacted];

  if (opts.json) {
    const output = JSON.stringify({ base, changed: changed.map(f => f.path), impacted: impacted.map(f => f.path) }, null, 2);
    if (opts.output) {
      fs.writeFileSync(path.resolve(opts.output), output, 'utf-8');
    } else {
      console.log(output);
    }
    return;
  }

  // Generate markdown review context for Claude
  const lines: string[] = [];
  lines.push(`# Code Review Context`);
  lines.push(`> Base: \`${base}\` | Generated by lumina`);
  lines.push(`> **Review only the files listed below** — do NOT scan the full source tree.`);
  lines.push(``);

  lines.push(`## Instructions for Claude`);
  lines.push(`1. Review the **Changed Files** section first — these were directly modified in the MR.`);
  lines.push(`2. Then check **Impacted Files** — these import the changed files and may be affected.`);
  lines.push(`3. Focus your review on correctness, edge cases, and regressions in the impact chain.`);
  lines.push(`4. Do not open or analyze files outside this list unless a review finding requires it.`);
  lines.push(``);

  lines.push(`## Changed Files (${changed.length})`);
  lines.push(``);
  lines.push(`| File | Type | Complexity | Risk |`);
  lines.push(`|------|------|-----------|------|`);
  for (const f of changed) {
    const risk = f.riskScore > 20 ? '🔥 High' : f.riskScore > 5 ? '⚠️ Medium' : '✅ Low';
    lines.push(`| \`${f.path}\` | ${f.type} | ${f.complexity} | ${risk} |`);
  }
  lines.push(``);

  lines.push(`## Impacted Files (${impacted.length})`);
  lines.push(`> These files import — directly or transitively — one or more of the changed files.`);
  lines.push(``);

  if (impacted.length === 0) {
    lines.push(`_No downstream files impacted._`);
  } else {
    lines.push(`| File | Type | Imported By | Risk |`);
    lines.push(`|------|------|-------------|------|`);
    for (const f of impacted) {
      const risk = f.riskScore > 20 ? '🔥' : f.riskScore > 5 ? '⚠️' : '✅';
      lines.push(`| \`${f.path}\` | ${f.type} | ${f.importedByCount} | ${risk} |`);
    }
  }
  lines.push(``);

  // Cycles warning for changed files
  const relevantCycles = saved.cycles.filter(cycle =>
    cycle.some(f => changedSet.has(f))
  );
  if (relevantCycles.length > 0) {
    lines.push(`## ⚠️ Circular Dependencies Involving Changed Files`);
    lines.push(``);
    for (const cycle of relevantCycles) {
      lines.push(`- ${cycle.map(f => `\`${f}\``).join(' → ')}`);
    }
    lines.push(``);
    lines.push(`> Changes in circular dep chains can cause unexpected side effects. Review these paths carefully.`);
    lines.push(``);
  }

  // Token estimation
  let reviewBytes = 0;
  for (const f of allFiles) {
    const abs = path.join(root, f.path);
    try { reviewBytes += fs.statSync(abs).size; } catch { /* skip */ }
  }

  let fullRepoBytes = 0;
  for (const rel of Object.keys(saved.files)) {
    const abs = path.join(root, rel);
    try { fullRepoBytes += fs.statSync(abs).size; } catch { /* skip */ }
  }

  const BYTES_PER_TOKEN = 4;
  const OVERHEAD_TOKENS = 3000; // system prompt + review context + query
  const reviewTokens = Math.round(reviewBytes / BYTES_PER_TOKEN) + OVERHEAD_TOKENS;
  const fullRepoTokens = Math.round(fullRepoBytes / BYTES_PER_TOKEN) + OVERHEAD_TOKENS;
  const savedTokens = fullRepoTokens - reviewTokens;
  const savingPct = Math.round((1 - reviewTokens / fullRepoTokens) * 100);

  // Cost at Claude Sonnet pricing ($3/MTok input)
  const COST_PER_TOKEN = 3 / 1_000_000;
  const reviewCost = (reviewTokens * COST_PER_TOKEN).toFixed(4);
  const fullCost = (fullRepoTokens * COST_PER_TOKEN).toFixed(4);

  lines.push(`---`);
  lines.push(`**Total files to review: ${allFiles.length}** (${changed.length} changed + ${impacted.length} impacted)`);
  lines.push(`vs full repo: **${saved.totalFiles} files** — saving ${Math.round((1 - allFiles.length / saved.totalFiles) * 100)}% scan effort`);
  lines.push(``);
  lines.push(`## Token Estimate`);
  lines.push(``);
  lines.push(`| | Lumina review | Full repo scan |`);
  lines.push(`|---|---|---|`);
  lines.push(`| Files | ${allFiles.length} | ${saved.totalFiles} |`);
  lines.push(`| Input tokens | ~${reviewTokens.toLocaleString()} | ~${fullRepoTokens.toLocaleString()} |`);
  lines.push(`| Est. cost (Sonnet $3/MTok) | ~$${reviewCost} | ~$${fullCost} |`);
  lines.push(`| Tokens saved | | **~${savedTokens.toLocaleString()} (${savingPct}%)** |`);

  const content = lines.join('\n');

  if (opts.output) {
    const outPath = path.resolve(opts.output);
    fs.writeFileSync(outPath, content, 'utf-8');
    console.log(pc.green('✓') + ` Review context saved: ${outPath}`);
    console.log(pc.dim(`  ${changed.length} changed + ${impacted.length} impacted = ${allFiles.length} files to review (of ${saved.totalFiles} total)`));
    console.log(pc.dim(`  ~${reviewTokens.toLocaleString()} tokens (~$${reviewCost}) vs full scan ~${fullRepoTokens.toLocaleString()} tokens (~$${fullCost})`));
  } else {
    console.log(content);
  }
}
